name: Documentation

on:
  push:
    branches:
      - main
    tags: '*'
  pull_request:

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: 'true'
      - uses: julia-actions/setup-julia@v2
        with:
          version: '1'
      - uses: julia-actions/cache@v2
      - name: Install dependencies
        run: |
          julia --project=docs/ -e 'using Pkg; Pkg.activate("docs"); Pkg.instantiate()'
          julia --project=. -e 'using Pkg; Pkg.activate("."); Pkg.instantiate()'
      - name: Build and deploy
        working-directory: docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: julia --project make.jl
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/build
  deploy:
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-22.04
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
